Post/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  # para mainclude ung views ng tweets app
from django.conf import settings
from django.conf.urls.static import static

from comment.views import comment_post, delete_comment
from .import views
from .views import *
from templates import *


urlpatterns = [
    path('profile/<str:username>/<int:post_id>/like/', like, name='like'),
    path('get-likes/<str:username>/<int:post_id>', views.get_likes, name='get_likes'),
    path('profile/<str:username>/<int:post_id>/likedby', likedby, name='likedby'),
    path('profile/<str:username>/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('comment_post/<int:post_id>', comment_post, name='comment_post'),
    path('profile/<str:username>/<int:post_id>/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
]

Post/models.py
import os
import random

from django.db import models
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save

from accounts.models import UserAccount
from django.dispatch import receiver


# Create your models here.
def get_filename_ext(filepath):
    base_name = os.path.basename(filepath)
    name, ext = os.path.splitext(base_name)
    return name, ext


def upload_picture_path(instance, filename):
    new_filename = random.randint(1, 3910209312)
    name, ext = get_filename_ext(filename)
    final_filename = '{new_filename}{ext}'.format(new_filename=new_filename, ext=ext)
    return 'pictures/{final_filename}'.format(new_filename=new_filename, final_filename=final_filename)


class Post(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField(max_length=500, blank=True, null=True)
    post_type = models.CharField(max_length=20, choices=[('picture', 'Picture'), ('video', 'Video')], default=None,
                                 null=True)
    picture = models.ImageField(upload_to=upload_picture_path, blank=True, null=True, default=None)
    video = models.FileField(upload_to='videos/', blank=True, null=True, default=None)
    updated = models.DateTimeField(auto_now=True)
    createdAt = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)
    liked_by = models.ManyToManyField(UserAccount, related_name='liked_posts', blank=True)

    def __str__(self):
        if self.post_type == 'picture':
            return os.path.basename(self.picture.name)
        if self.post_type == 'video':
            return os.path.basename(self.video.name)
        else:
            return str(self.content)

    def __repr__(self):
        return f"Post('{self.content}', '{self.createdAt}')"

    def create_post(self, content, user, post_type=None, picture=None, video=None):
        post = Post()
        post.content = content
        post.user = user
        post.post_type = post_type
        post.picture = picture
        post.video = video
        post.save()
        return post




@receiver(post_save, sender=Post)
def create_post(sender, instance, created, **kwargs):
    if created:
        UserLike.objects.create(voter=instance.user, post=instance)


class UserLike(models.Model):
    voter = models.ForeignKey(UserAccount, on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    is_liked = models.BooleanField(default=False)

    class Meta:
        unique_together = ('voter', 'post')

    def __str__(self):
        return str(self.voter)

testimonials/models.py
from django.db import models
from django.conf import settings
from accounts.models import UserAccount
from django.utils import timezone
from django.core.validators import MinValueValidator, MaxValueValidator

# Create your models here.
class Testimonial(models.Model):
    user_from = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name='testimonials_given')
    user_to = models.ForeignKey(UserAccount, on_delete=models.CASCADE, related_name='testimonials_received')
    content = models.TextField()
    createdAt = models.DateTimeField(default=timezone.now)
    # rating = models.PositiveIntegerField(
    #     default=0,
    #     validators=[
    #         MinValueValidator(1, "Rating must be at least 1"),
    #         MaxValueValidator(5, "Rating cannot be more than 5")
    #     ]
    # )

    def __str__(self):
        return f"Testimonial from {self.user_from.username} to {self.user_to.username}"

    def __repr__(self):
        return f"Testimonial('{self.content}', '{self.createdAt}')"

Post/forms.py
# forms.py
from django import forms
from .models import Post


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['content', 'picture', 'video', 'post_type']

    def __init__(self, *args, **kwargs):
        super(PostForm, self).__init__(*args, **kwargs)
        # Make the 'post_type' field not required
        self.fields['post_type'].required = False

    def clean(self):
        cleaned_data = super().clean()
        post_type = cleaned_data.get('post_type')
        content = cleaned_data.get('content')

        # If the post_type is 'picture', the content field is not required.
        if post_type == 'picture':
            if not content:
                # Set content to an empty string if not provided
                cleaned_data['content'] = ''
        return cleaned_data

testimonials/forms.py
from django import forms
from django.core.validators import MinValueValidator, MaxValueValidator

from accounts.models import UserAccount
from .models import Testimonial


class TestimonialForm(forms.ModelForm):
    class Meta:
        model = Testimonial
        fields = ['content']

    user_to = forms.ModelChoiceField(
        queryset=UserAccount.objects.all(),
        widget=forms.HiddenInput(),  # Use a hidden input field
        required=False  # Make the field non-required
    )

    # rating = forms.IntegerField(
    #     label='Rating',
    #     widget=forms.NumberInput(attrs={'type': 'number', 'min': 1, 'max': 5}),
    #     validators=[MinValueValidator(1), MaxValueValidator(5)]
    # )
    def clean(self):
        cleaned_data = super().clean()
        content = cleaned_data.get('content')

        if not content:
            raise forms.ValidationError('Testimonial content is required.')

Post/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse, HttpResponseForbidden, Http404
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView

from accounts.models import UserAccount
from comment.forms import CommentForm
from comment.models import Comment
from .models import Post, UserLike
from django.urls import reverse_lazy
from django import forms
from Post.forms import PostForm
from django.contrib import messages


@login_required
def create_post(request, username):
    if request.user.username != username:
        raise Http404("You are not allowed to create a post on this profile.")

    if request.method == 'POST':
        form = PostForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            user = request.user
            print('shet')
            print(request.POST)
            post = form.save(commit=False)
            post.user = user
            post.save()

            return redirect('profile', username=username)
    else:
        form = PostForm()

    return render(request, 'posts/post.html', {'form': form})


@login_required
def post_detail(request, username, post_id):
    user = get_object_or_404(UserAccount, username=username)
    post = get_object_or_404(Post, pk=post_id, user=user)
    comments = Comment.objects.filter(post=post)  # Get the comments for the post

    user_like = None
    if request.user.is_authenticated:
        try:
            user_like = UserLike.objects.get(voter=request.user, post=post)
        except UserLike.DoesNotExist:
            user_like = None

    # Instantiate an empty comment form
    comment_form = CommentForm()

    if request.method == 'POST':
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.user = request.user
            new_comment.save()
            return redirect('post_detail', username=username, post_id=post_id)

    return render(request, 'Posts/posts_detail.html', {
        'user': user,
        'post': post,
        'user_like': user_like,
        'comments': comments,  # Add the comments to the context
        'comment_form': comment_form,  # Add the comment form to the context
    })




@login_required
def like(request, username, post_id):
    user = request.user
    target_post = Post.objects.get(pk=post_id)

    try:
        user_like, created = UserLike.objects.get_or_create(voter=user, post=target_post)

        if created:
            target_post.likes += 1
            target_post.save()
            target_post.likes.add(user)
        elif not user_like.is_liked:
            user_like.is_liked = True
            user_like.save()
            target_post.likes += 1
            target_post.save()
            target_post.liked_by.add(user)
        else:
            user_like.is_liked = False
            user_like.save()
            target_post.likes -= 1
            target_post.save()
            target_post.liked_by.remove(user)

        return JsonResponse({'likes': target_post.likes})
    except Post.DoesNotExist:
        return JsonResponse({'error': 'The post does not exist.'}, status=404)


@login_required
def get_likes(request, post_id, username):
    post = get_object_or_404(Post, pk=post_id)
    liked_users = [user.username for user in post.liked_by.all()]
    return JsonResponse({'liked_users': liked_users})


@login_required
def likedby(request, post_id, username):
    post = Post.objects.get(id=post_id)
    liked_users = UserLike.objects.filter(post=post, is_liked=True)
    return render(request, 'posts/liked_by.html', {'post': post, 'liked_users': liked_users})


@login_required
def delete_post(request, username, post_id):
    try:
        post = Post.objects.get(id=post_id)
        if request.user == post.user or request.user.is_superuser:
            # Only allow deletion if the logged-in user is the owner of the post
            post.delete()
            return redirect('profile', username=username)
        else:
            # If the logged-in user is not the owner, return a forbidden response
            return HttpResponseForbidden("You are not allowed to delete this post.")
    except Post.DoesNotExist:
        pass

    return redirect('profile', username=username)


# @login_required
# def customization(request, username):
#     if request.method == 'POST':
#         form = PostForm(request.POST, request.FILES)
#         if form.is_valid():
#             user = request.user
#
#             post = form.save(commit=False)
#             post.user = user
#             post.save()
#
#             return redirect('profile', username=username)
#     else:
#         form = PostForm()
#
#     return render(request, 'customization/customization.html', {'form': form})

testimonials/views.py
from django.db.models import Avg
from django.http import HttpResponseForbidden, JsonResponse
from django.urls import reverse
from .models import *
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from .forms import TestimonialForm
from accounts.models import UserAccount
from django.contrib.auth.decorators import login_required

@login_required
def add_testimonial(request, user_to_username):
    user_to = get_object_or_404(UserAccount, username=user_to_username)

    if user_to == request.user:
        return HttpResponseForbidden("You cannot post a testimonial on your own profile.")

    if request.method == 'POST':
        form = TestimonialForm(request.POST)
        if form.is_valid():
            testimonial = form.save(commit=False)
            testimonial.user_from = request.user
            testimonial.user_to = user_to
            testimonial.save()
            print("Testimonial saved successfully")
            form.cleaned_data['content'] = ""

            return redirect('profile', username=user_to.username)
        else:
            print("Form errors:", form.errors)
    else:
        form = TestimonialForm(initial={'user_to': user_to})

    return render(request, 'posts/testimonials.html', {'form': form})


def view_testimonials(request, user_to_username):
    # Debug print to check if user_to_username is correct
    print("user_to_username:", user_to_username)

    user = get_object_or_404(UserAccount, username=user_to_username)
    # Debug print to check if the correct user is retrieved
    print("User retrieved:", user)

    # Check if the logged-in user is viewing their own profile or another user's profile
    if user == request.user:
        # If the user is viewing their own profile
        testimonials_received = Testimonial.objects.filter(user_to=user).order_by('-createdAt')
    else:
        # If the user is viewing another user's profile
        testimonials_received = Testimonial.objects.filter(user_to=user).order_by('-createdAt')

    return render(request, 'testimonial/view_testimonial.html', {
        'user': user,
        'testimonials_received': testimonials_received,
    })

@login_required
def testimonial_detail(request, user_to_username, testimonial_id):
    user = get_object_or_404(UserAccount, username=user_to_username)
    testimonial = get_object_or_404(Testimonial, pk=testimonial_id, user_to=user)
    came_from = request.GET.get('came_from', 'profile')  # Get the 'came_from' parameter from the URL
    return render(request, 'testimonial/testimonial_detail.html', {'testimonial': testimonial, 'came_from': came_from})


from django.shortcuts import redirect


# ...

@login_required
def delete_testimonial(request, user_to_username, testimonial_id):
    testimonial = get_object_or_404(Testimonial, pk=testimonial_id)

    # Check if the logged-in user is either the sender or receiver of the testimonial
    if request.user == testimonial.user_from or request.user == testimonial.user_to or UserAccount.is_superuser:
        # Delete the testimonial
        testimonial.delete()
        came_from = request.GET.get('came_from', 'profile')  # Get the 'came_from' parameter from the URL

        # Determine the redirect URL based on 'came_from'
        if came_from == 'view_testimonials':
            # Redirect to the profile view
            return redirect('view_testimonials', user_to_username=user_to_username)

        else:
            # Redirect to the view_testimonials page by default
            return redirect('profile', username=user_to_username)
    else:
        # If the logged-in user is not the sender or receiver, return a forbidden response
        return HttpResponseForbidden("You are not allowed to delete this testimonial.")

templates/posts/liked_by.html
{% extends "profile/header.html" %}
{% load static %}
{% block content %}

<div class="container">
    <h1>Liked By</h1>
    <div class="liked-users-container">
        {% if liked_users %}
            {% for user in liked_users %}
                <a href="{% url 'profile' username=user %}" class="liked-user-card">
                    <div class="liked-user-profile-image">
                        <img src="{{ user.profile_image.url }}" alt="">
                    </div>
                    <div class="liked-user-username">
                        {{ user }}
                    </div>
                </a>
            {% endfor %}
        {% else %}
            <h4>No users have liked this post yet.</h4>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/posts/list_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% for foo in object_list %}
    {{ foo.user }} <br>
    {{ foo.content }} <br>
    {{ foo.createdAt }}<br>
    {{ foo.createdAt | timesince }}<br>

{% endfor %}
</body>
</html>

templates/posts/post.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Create a New Post</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, minimum-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet">
    <link href="{% static 'profile/post.css' %}" rel="stylesheet">
    <link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>
    <div class="post-container">
        <header><h1>Create Post</h1></header>

        <form method="post" enctype="multipart/form-data" id="post-form">
            {% csrf_token %}
            <div class="input-box">
            <textarea class="post-field" name="{{ form.content.name }}" id="{{ form.content.id_for_label }}" oninput="enableSubmitButton()" placeholder="What's on your mind?"></textarea>
            </div>

            <label>Select Type:</label>
            <label for="{{ form.post_type.id_for_label }}">
                <input type="radio" name="{{ form.post_type.name }}" value="picture" id="{{ form.post_type.id_for_label }}"> Picture
            </label>
            <label for="{{ form.post_type.id_for_label }}">
                <input type="radio" name="{{ form.post_type.name }}" value="video" id="{{ form.post_type.id_for_label }}"> Video
            </label>

            <div id="picture-upload" style="display: none;">
                <label for="{{ form.picture.id_for_label }}">Upload Picture:</label>
                <input type="file" name="{{ form.picture.name }}" id="{{ form.picture.id_for_label }}">
            </div>

            <div id="video-upload" style="display: none;">
                <label for="{{ form.video.id_for_label }}">Upload Video:</label>
                <input type="file" name="{{ form.video.name }}" id="{{ form.video.id_for_label }}">
            </div>

            <input id="submit-btn" type="submit"  value="Create Post">
        </form>


     <script>
    document.addEventListener('DOMContentLoaded', function() {
        let pictureRadio = document.querySelector('input[value="picture"]');
        let videoRadio = document.querySelector('input[value="video"]');
        let pictureInput = document.querySelector('input[name="{{ form.picture.name }}"]');
        let videoInput = document.querySelector('input[name="{{ form.video.name }}"]');
        let contentInput = document.querySelector('input[name="{{ form.content.name }}');

        let currentSelection = null;

        pictureRadio.addEventListener('change', function() {
            toggleUploadSection('picture-upload', 'video-upload', pictureInput, videoInput);
        });

        videoRadio.addEventListener('change', function() {
            toggleUploadSection('video-upload', 'picture-upload', videoInput, pictureInput);
        });

        function toggleUploadSection(showSectionId, hideSectionId, showFileInput, hideFileInput) {
            let showSection = document.getElementById(showSectionId);
            let hideSection = document.getElementById(hideSectionId);

            hideFileInput.disabled = true;

            if (currentSelection === showSectionId) {
                return;
            }

            showFileInput.value = '';
            showFileInput.disabled = false;

            showSection.style.display = 'block';
            hideSection.style.display = 'none';

            currentSelection = showSectionId;
            enableSubmitButton(contentInput, pictureInput, videoInput);
        }

        function enableSubmitButton(contentInput, pictureInput, videoInput) {
            // Get the submit button
            const submitButton = document.getElementById('submit-btn');
            const errorMessages = document.getElementById('error-messages');
            errorMessages.innerHTML = ''; // Clear previous error messages

            // Check if content is not empty or either picture or video input has a file selected
            if (contentInput.value.trim() !== '' || (pictureInput.files.length > 0 && validateFileExtensions(pictureInput)) || (videoInput.files.length > 0 && validateFileExtensions(videoInput))) {
                submitButton.disabled = false;
            } else {
                submitButton.disabled = true;
                errorMessages.innerHTML = 'Please fill out all required fields and upload a valid picture or video file.';
            }
        }

        function validateFileExtensions(fileInput) {
            // Allowed file extensions for picture and video
            const allowedPictureExtensions = ['.jpg', '.jpeg', '.png', '.gif'];
            const allowedVideoExtensions = ['.mp4', '.avi', '.mov', '.mkv'];

            // Helper function to get the file extension from a filename
            function getFileExtension(filename) {
                return filename.split('.').pop().toLowerCase();
            }

            if (fileInput.files.length > 0) {
                const fileExtension = getFileExtension(fileInput.files[0].name);
                if (fileInput === pictureInput) {
                    if (!allowedPictureExtensions.includes('.' + fileExtension)) {
                        errorMessages.innerHTML = 'Invalid picture file format. Please select a valid image file.';
                        return false;
                    }
                } else if (fileInput === videoInput) {
                    if (!allowedVideoExtensions.includes('.' + fileExtension)) {
                        errorMessages.innerHTML = 'Invalid video file format. Please select a valid video file.';
                        return false;
                    }
                }
            }

            return true;
        }

        // Add event listeners for file inputs to trigger validation
        pictureInput.addEventListener('change', function() {
            enableSubmitButton(contentInput, pictureInput, videoInput);
        });
        videoInput.addEventListener('change', function() {
            enableSubmitButton(contentInput, pictureInput, videoInput);
        });

        // Initial validation
        enableSubmitButton(contentInput, pictureInput, videoInput);
    });
</script>


</body>
</html>

templates/posts/testimonials.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Make A Testimonial</title>
  <link rel="stylesheet" href="{% static 'profile/testimonials.css' %}">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Raleway:wght@700&display=swap" rel="stylesheet">
</head>
<body>
	<div class="testimonial-container">
		<header><h1>Create a Testimonial</h1></header>

		<form method="post" id="testimonial-form">
			{% csrf_token %}
{#			<label id="rate">Rating:</label>#}

{#			<div class="rating">#}
{#				<label>#}
{#					<input type="radio" name="rating" value="1" />#}
{#					<span class="icon">★</span>#}
{#				</label>#}
{#				<label>#}
{#					<input type="radio" name="rating" value="2" />#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#				</label>#}
{#				<label>#}
{#					<input type="radio" name="rating" value="3" />#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#				</label>#}
{#				<label>#}
{#					<input type="radio" name="rating" value="4" />#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#				</label>#}
{#				<label>#}
{#					<input type="radio" name="rating" value="5" />#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#					<span class="icon">★</span>#}
{#				</label>#}
{#			</div>#}

{#			<label for="id_content">Testimonial Content:</label>#}
            <div class="input-box">
            <textarea id="id_content" name="content" rows="4" cols="50" class="testimonial-field" oninput="enableSubmitButton()" placeholder="What's on your mind?"></textarea>
            </div>

            <input type="hidden" name="user_to_username" value="{{ user_to.username }}">
            <input id="submit-btn" type="submit" value="Add Testimonial" disabled>
        </form>
	</div>
<script>
        function enableSubmitButton() {
            // Get the testimonial content
            const content = document.getElementById('id_content').value;

            // Get the submit button
            const submitButton = document.getElementById('submit-btn');

            // Enable the button if content is not empty, otherwise disable it
            if (content.trim() !== '') {
                submitButton.disabled = false;
            } else {
                submitButton.disabled = true;
            }
        }
</script>
</body>
</html>