Post/urls.py
from django.contrib import admin
from django.urls import path, include, re_path  # para mainclude ung views ng tweets app
from django.conf import settings
from django.conf.urls.static import static

from comment.views import comment_post, delete_comment
from .import views
from .views import *
from templates import *


urlpatterns = [
    path('profile/<str:username>/<int:post_id>/like/', like, name='like'),
    path('get-likes/<str:username>/<int:post_id>', views.get_likes, name='get_likes'),
    path('profile/<str:username>/<int:post_id>/likedby', likedby, name='likedby'),
    path('profile/<str:username>/<int:post_id>/delete/', delete_post, name='delete_post'),
    path('comment_post/<int:post_id>', comment_post, name='comment_post'),
    path('profile/<str:username>/<int:post_id>/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
]

contact/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from contact.views import *

urlpatterns = [
    path('contact/', contact_view, name='contact'),
    path('send_email/<str:subject>/<str:email>/<str:name>/', send_email, name='send_email'),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + \
                  static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/models.py
from django.utils import timezone
from django.db import models


# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(max_length=100)
    comment = models.TextField(null=True, blank=True)
    subject = models.TextField(max_length=200, null=True, blank=True)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.name

contact/forms.py
from django import forms
from .models import Contact


# class Contact(forms.ModelForm):
#     class Meta:
#         model = Contact
#         fields = ['name', 'email', 'subject', 'comment']

# class ContactForm(forms.Form):
#     name = forms.CharField(label='Your Name', max_length=100)
#     email = forms.EmailField(label='Your Email')
#     subject = forms.CharField(max_length=100)
#     message = forms.CharField(widget=forms.Textarea, label='Your Message')

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'comment']

contact/views.py
from django.conf import settings
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from django.core.mail import send_mail
from .forms import ContactForm
from .models import Contact

# def contact_view(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             name = form.cleaned_data['name']
#             email = form.cleaned_data['email']
#             message = form.cleaned_data['message']
#
#             # Save the contact form data to the database
#             Contact.objects.create(name=name, email=email, comment=message, subject=form.cleaned_data['subject'])
#
#             # Send email from the user's email address
#             send_mail(
#                 f'Contact Form Submission from {name}',
#                 message,
#                 email,  # Use the user's email as the 'from_email'
#                 ['HAUGabster@gmail.com'],  # Replace with your admin's email address
#                 fail_silently=False,
#             )
#             print(f'Sending email from: {email}')
#             return redirect('contact_success')  # Redirect to a "Thank you" page or desired location after submission
#     else:
#         form = ContactForm()
#
#     return render(request, 'contact/contact.html', {'form': form})
def contact_view(request):
    contacts = None

    if request.user.is_superuser:
        contacts = Contact.objects.all().order_by('created_at')

    if request.method == "POST":

        name = request.POST.get("name")
        email = request.POST.get("email")
        subject = request.POST.get("subject")
        comment = request.POST.get("comment")
        query = Contact(name=name, email=email, subject=subject, comment=comment)
        query.save()
        success_message = "Your message has been sent successfully."
        return render(request, 'contact/contact.html', {'contacts': contacts, 'success_message': success_message})

    return render(request, 'contact/contact.html', {'contacts': contacts})
def send_email(request, subject, email, name):
    subject = ('Re:' + subject)
    email = email
    name = name
    print(subject)

    if request.method == "POST":
        print("request.POST")
        message = request.POST.get("message")
        message_data = {
            'name': name,
            'email': email,
            'comment': message,
            'subject': subject,

        }
        html_message = render_to_string('contact/email_template.html', message_data)
        plain_message = strip_tags(html_message)

        if subject and message and email:
            try:
                send_mail(subject, plain_message, settings.EMAIL_HOST_USER, [email], html_message=html_message)
                return redirect('/')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
        else:
            return HttpResponse('Invalid form data')
    context = {
        'subject': subject,
        'email': email,
        'name': name,
    }
    return render(request, 'contact/email_response.html', context)

templates/contact/contact.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
    <title>Contact Us</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css?family={{ user.font_preference }}" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@600&family=Roboto&display=swap" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <meta name=”viewport” content=”width=device-width, initial-scale=1.0">
    <link href="{% static 'profile/contact.css' %}" rel="stylesheet">
    <link id="theme-style" rel="stylesheet" type="text/css" href="">
</head>
<body>
            {% if user.is_superuser %}
    <div class="testimonial-container" style="padding: 100px 100px 100px 100px; background-color: black">
            <div style="padding-bottom: 20px">
            <div class="wrapper" style="padding: 10px 20px 5px 20px">
                <header><h1>Contact Page</h1></header>
            </div>
        </div>

{#                    {% for contact in contacts %}#}
        <div class="row">
            <div class="col-md-12">
                <div class="contacts">
                    <div class="card rounded">
                        <div style="padding: 20px 10px 10px;" class="card-header">
                            <div class="d-flex align-items-center justify-content-between">
                                <div class="d-flex align-items-center">
                                    <div class="d-flex justify-content-between">
                                        <h5><strong>Name:</strong> {{ contact.name }}</h5>
                                        <p class="tx-11 text-muted">{{ contact.email }}</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div>
                            <div class="contacts-body">
                                <p><strong>Subject:</strong> {{ contact.subject }}</p>
                                <p><strong>Message:</strong> {{ contact.comment }}</p>
{#                                <a href="{% url 'send_email' contact.subject contact.email contact.name %}">#}
                                    <button id="submit-btn">Respond</button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
{#                {% endfor %}#}
    </div>
{#                <h1 class="text-3xl font-bold mb-4 uppercase text-center">Contact Messages</h1>#}
{#                <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">#}
{#                    {% for contact in contacts %}#}
{#                        <div class="bg-white rounded-lg shadow-xl p-4">#}
{#                            <p><strong>Name:</strong> {{ contact.name }}</p>#}
{#                            <p><strong>Email:</strong> {{ contact.email }}</p>#}
{#                            <p><strong>Subject:</strong> {{ contact.subject }}</p>#}
{#                            <p><strong>Message:</strong> {{ contact.comment }}</p>#}
{#                            <a href="{% url 'send_email' contact.subject contact.email contact.name %}">#}
{#                                <button id="submit-btn">Respond</button>#}
{#                            </a>#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                </div>#}
            {% else %}
                <div class="wrapper">
                <div class="flex justify-center items-center">
                    <div>
                        <header><h1>Contact Us!</h1></header>
                        <form method="post">
                            {% csrf_token %}
                            <div class="input-box">
                                <input type="text" name="name" id="name" class="form-control" placeholder="Name" required>
                            </div>

                             <div class="input-box">
                                <input type="email" id="email" name="email" class="form-control" placeholder="Email" required>
                            </div>

                            <div class="input-box">
                                <input type="text" id="subject" name="subject" class="form-control" placeholder="Subject" required>
                            </div>

                            <div class="input-box">
                                <textarea id="comment" name="comment" class="post-field" placeholder="Leave a Comment Here" style="height: 100px" required></textarea>
                            </div> <br>
                                <input id="submit-btn" type="submit"  data-bs-target="#successModal">
{#                            <button type="submit" class="w-full py-2 px-4 text-white rounded-lg bg-red-800 hover:bg-red-700" data-bs-target="#successModal">SUBMIT</button>#}
                        </form>
                    </div>
                </div>
            </div>
            {% endif %}
            <!-- Modal for Success Message -->
        <div class="modal fade" id="successModal" tabindex="-1" aria-labelledby="successModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="successModalLabel">Success</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                        Your message has been sent successfully.
                    </div>
                </div>
            </div>
        </div>

        <script src="https://kit.fontawesome.com/1aebf17ad5.js" crossorigin="anonymous"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"></script>
        {% if success_message %}
            <script>
                // Show the success modal
                $(document).ready(function() {
                    $('#successModal').modal('show');
                });
            </script>
        {% endif %}

</body>
</html>

templates/contact/contact_success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
nice
</body>
</html>

templates/contact/email_response.html
{% extends 'profile/header.html' %}
{% block title %}Response {% endblock %}

{% block content %}
        <div class="container-xxl mb-2">
            <div class="col-md-6 flex items-center justify-center">
                <div class="card shadow-lg w-80 text-center min-h-full">
                    <div class="card-body p-5 text-center">
                        <h2 class="mb-4 uppercase font-bold text-xl">Response</h2>
                        <form method="post">
                            {% csrf_token %}
                            <div class="mb-3">
                                <label for="id_name" class="form-label uppercase font-bold">Name:</label>
                                <input type="text" disabled name="name" id="id_name" class="form-control bg-gradient-orange" value="{{ name }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_email" class="form-label uppercase font-bold">Email:</label>
                                <input type="email" disabled name="email" id="id_email" class="form-control bg-gradient-orange" value="{{ email }}">
                            </div>
                            <div class="mb-3">
                                <label for="id_subject" class="form-label uppercase font-bold">Subject:</label>
                                <input type="text" disabled name="subject" id="id_subject" class="form-control bg-gradient-orange" value="{{ subject }}">
                            </div>
                            <div class="mb-4">
                                <label for="id_message" class="form-label uppercase font-bold">Message</label>
                                <textarea name="message" id="id_message" class="mt-2 form-control border border-black rounded-lg p-2 text-md" placeholder="Type here..." rows="4"></textarea>
                            </div>
                            <button class="uppercase font-bold px-2 py-3 text-white rounded-xl" type="submit" style="background: {{ user.profile.color }}">Submit</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}

templates/contact/email_template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contact Us</title>
    <style>
        body {
            font-family: Poppins, sans-serif;
            background-color: #fe8116;
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #cc5d00;
            border-radius: 5px;
            box-shadow: 0 0 5px rgba(0, 0, 0, 0.3);
        }
        .text-center {
            text-align: center;
        }
        .contact-details {
            margin-top: 20px;
        }
        .contact-details p {
            margin: 5px 0;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1 class="text-center font-bold">CONTACT US - RESPONSE</h1>
        <div class="contact-details text-center">
            <p><strong>Name:</strong> {{ name }}</p><br>
            <p><strong>Email:</strong> {{ email }}</p><br>
            <p><strong>Subject:</strong> {{ subject }}</p><br>
            <p><strong>Comment:</strong><br> {{ comment }}</p><br><br><br><br>
            <div class="mt-3 text-center text-gray-500">
                PLEASE NOTE: You cannot reply to this e-mail as it is only a response message.
                If you have any more concerns, please contact us using our website HAU Marketplace.
            </div>
        </div>
    </div>
</body>
</html>